namespace Learning_experience.Pages.Features
{
    /* Exceptions   Tre errors in Runtime is propagetes using a mechanism called exceptions.
     * Exceptions are thrown by code that encounters an error and caught by code that can correct the error.
     -Exceptions can be generated by both .NET runtime or a program code.
    - All exception must derive from Exception class
    - The throw keyword is used for generating an exception
    - The try-catch-finally block can be used to catch and process exceptions
    - Some exceptions can not be handled or required additional handling, for exemple StackOverFlowException and 
    TreadAbroadException*/
    /*StackTrace is the best way to see, what is the problem. Also inner exception and message*/
    public class Exceptions
    {
        class ExceptionTestClass
        {
            public static void Main()
            {
                int x = 0;
                try
                {
                    int y = 100 / x;
                }
                catch (ArithmeticException e)
                {
                    Console.WriteLine($"ArithmeticException Handler: {e}");
                }
                catch (Exception e)
                {
                    Console.WriteLine($"Generic Exception Handler: {e}");
                }
            }
        }
        /*
        This code example produces the following results:

        ArithmeticException Handler: System.DivideByZeroException: Attempted to divide by zero.
           at ExceptionTestClass.Main()

        */
    }
}
